version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    reviewers:
      - "boul2gom"
    assignees:
      - "boul2gom"
    commit-message:
      prefix: "🦀 [Rust Crates] "
    target-branch: "develop"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    reviewers:
      - "boul2gom"
    assignees:
      - "boul2gom"
    commit-message:
      prefix: "🔌 [Github Actions] "
    target-branch: "develop"
    rebase-strategy: "auto"