name: Github CI - Automatic Biweekly Release

on:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📁 Check out the repository
        uses: actions/checkout@v4.2.2

      - name: 📦 Cache Rust toolchain
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-toolchain-

      - name: 🛠️ Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: 📌 Install cargo-release
        run: cargo install cargo-release

      - name: 🚀 Create a new patch release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo release patch

      - name: 🔍 Get new version
        id: get_version
        run: echo "version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

      - name: 📝 Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: 🔖 v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false